[package]
name = "tick_tackun"
version = "0.1.0"
edition = "2021"
readme = "README.md"
license-file = "LICENSE.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
